#!/bin/sh 
tmux new-session -s xyz -n development 'docker-compose up --build' \; split-window -c cms -v 'grunt watch' \; split-window -c www -h 'grunt watch' \; select-pane -t 0 \;
#tmux split-window -v
#tmux split-window -h

#tmux select-window -t xyz:0
#tmux split-window -v 'ping -c 3 127.0.0.1'

tmux select-window -t xyz:0
tmux -2 attach-session -t xyz

#tmux new-session -s foo 'exec cd /home/debugelton/nodeworkspace/herbpope"'
#tmux rename-window 'Foo'
#tmux select-window -t foo:0
#tmux split-window -h 'exec cd cms"'
#tmux split-window -v -t 0 'exec cd www"'
#tmux split-window -v -t 1 ''
#tmux -2 attach-session -t foo
